export const COUNTRY_TO_ISO3 = {
  'Afghanistan': 'AFG', 'Albania': 'ALB', 'Algeria': 'DZA', 'Angola': 'AGO',
  'Antigua and Barbuda': 'ATG', 'Argentina': 'ARG', 'Armenia': 'ARM',
  'Australia': 'AUS', 'Austria': 'AUT', 'Azerbaijan': 'AZE',
  'Bahamas': 'BHS', 'Bahrain': 'BHR', 'Bangladesh': 'BGD', 'Barbados': 'BRB',
  'Belarus': 'BLR', 'Belgium': 'BEL', 'Belize': 'BLZ', 'Benin': 'BEN',
  'Bhutan': 'BTN', 'Bolivia': 'BOL', 'Bosnia and Herzegovina': 'BIH',
  'Botswana': 'BWA', 'Brazil': 'BRA', 'Brunei': 'BRN', 'Bulgaria': 'BGR',
  'Burkina Faso': 'BFA', 'Burundi': 'BDI', 'Cabo Verde': 'CPV',
  'Cape Verde': 'CPV', 'Cambodia': 'KHM', 'Cameroon': 'CMR', 'Canada': 'CAN',
  'Central African Republic': 'CAF', 'Chad': 'TCD', 'Chile': 'CHL',
  'China': 'CHN', "China (People's Republic of)": 'CHN',
  'Colombia': 'COL', 'Comoros': 'COM', 'Congo': 'COG',
  'Congo, Rep.': 'COG', 'Congo, Dem. Rep.': 'COD',
  'Democratic Republic of the Congo': 'COD',
  'Republic of Congo': 'COG',
  'Costa Rica': 'CRI', "Côte d'Ivoire": 'CIV', "Cote d'Ivoire": 'CIV',
  "Côte D'Ivoire": 'CIV', 'Croatia': 'HRV', 'Cuba': 'CUB', 'Cyprus': 'CYP',
  'Czech Republic': 'CZE', 'Czechia': 'CZE',
  'Denmark': 'DNK', 'Djibouti': 'DJI', 'Dominica': 'DMA',
  'Dominican Republic': 'DOM', 'East Timor': 'TLS', 'Ecuador': 'ECU',
  'Egypt': 'EGY', 'El Salvador': 'SLV', 'Equatorial Guinea': 'GNQ',
  'Eritrea': 'ERI', 'Estonia': 'EST', 'Eswatini': 'SWZ', 'Swaziland': 'SWZ',
  'Ethiopia': 'ETH', 'Fiji': 'FJI', 'Finland': 'FIN', 'France': 'FRA',
  'Gabon': 'GAB', 'Gambia': 'GMB', 'Georgia': 'GEO', 'Germany': 'DEU',
  'Ghana': 'GHA', 'Greece': 'GRC', 'Guatemala': 'GTM', 'Guinea': 'GIN',
  'Guinea-Bissau': 'GNB', 'Guyana': 'GUY', 'Haiti': 'HTI', 'Honduras': 'HND',
  'Hungary': 'HUN', 'Iceland': 'ISL', 'India': 'IND', 'Indonesia': 'IDN',
  'Iran': 'IRN', 'Iraq': 'IRQ', 'Ireland': 'IRL', 'Israel': 'ISR',
  'Italy': 'ITA', 'Jamaica': 'JAM', 'Japan': 'JPN', 'Jordan': 'JOR',
  'Kazakhstan': 'KAZ', 'Kenya': 'KEN', 'Kiribati': 'KIR',
  'Kosovo': 'XKX', 'Kuwait': 'KWT', 'Kyrgyzstan': 'KGZ',
  'Kyrgyz Republic': 'KGZ', 'Laos': 'LAO', 'Lao PDR': 'LAO',
  'Latvia': 'LVA', 'Lebanon': 'LBN', 'Lesotho': 'LSO', 'Liberia': 'LBR',
  'Libya': 'LBY', 'Lithuania': 'LTU', 'Luxembourg': 'LUX',
  'Madagascar': 'MDG', 'Malawi': 'MWI', 'Malaysia': 'MYS',
  'Maldives': 'MDV', 'Mali': 'MLI', 'Malta': 'MLT',
  'Marshall Islands': 'MHL', 'Mauritania': 'MRT', 'Mauritius': 'MUS',
  'Mexico': 'MEX', 'Micronesia': 'FSM', 'Moldova': 'MDA',
  'Mongolia': 'MNG', 'Montenegro': 'MNE', 'Morocco': 'MAR',
  'Mozambique': 'MOZ', 'Myanmar': 'MMR', 'Burma': 'MMR',
  'Namibia': 'NAM', 'Nepal': 'NPL', 'Netherlands': 'NLD',
  'New Zealand': 'NZL', 'Nicaragua': 'NIC', 'Niger': 'NER',
  'Nigeria': 'NGA', 'North Korea': 'PRK', 'North Macedonia': 'MKD',
  'Norway': 'NOR', 'Oman': 'OMN', 'Pakistan': 'PAK', 'Palau': 'PLW',
  'Palestine': 'PSE', 'Palestinian Territories': 'PSE',
  'West Bank and Gaza': 'PSE', 'Gaza Strip': 'PSE',
  'West Bank': 'PSE', 'Occupied Palestinian Territory': 'PSE',
  'Panama': 'PAN', 'Papua New Guinea': 'PNG', 'Paraguay': 'PRY',
  'Peru': 'PER', 'Philippines': 'PHL', 'Poland': 'POL',
  'Portugal': 'PRT', 'Qatar': 'QAT', 'Romania': 'ROU',
  'Russia': 'RUS', 'Russian Federation': 'RUS', 'Rwanda': 'RWA',
  'Samoa': 'WSM', 'Sao Tome and Principe': 'STP', 'Saudi Arabia': 'SAU',
  'Senegal': 'SEN', 'Serbia': 'SRB', 'Sierra Leone': 'SLE',
  'Singapore': 'SGP', 'Slovakia': 'SVK', 'Slovenia': 'SVN',
  'Solomon Islands': 'SLB', 'Somalia': 'SOM', 'South Africa': 'ZAF',
  'South Korea': 'KOR', 'Republic of Korea': 'KOR', 'Korea': 'KOR',
  'South Sudan': 'SSD', 'Spain': 'ESP', 'Sri Lanka': 'LKA',
  'Sudan': 'SDN', 'Suriname': 'SUR', 'Sweden': 'SWE',
  'Switzerland': 'CHE', 'Syria': 'SYR', 'Syrian Arab Republic': 'SYR',
  'Taiwan': 'TWN', 'Tajikistan': 'TJK', 'Tanzania': 'TZA',
  'United Republic of Tanzania': 'TZA',
  'Thailand': 'THA', 'Timor-Leste': 'TLS', 'Togo': 'TGO',
  'Tonga': 'TON', 'Trinidad and Tobago': 'TTO', 'Tunisia': 'TUN',
  'Turkey': 'TUR', 'Turkmenistan': 'TKM', 'Tuvalu': 'TUV',
  'Uganda': 'UGA', 'Ukraine': 'UKR', 'United Arab Emirates': 'ARE',
  'United Kingdom': 'GBR', 'United States': 'USA',
  'United States of America': 'USA', 'Uruguay': 'URY',
  'Uzbekistan': 'UZB', 'Vanuatu': 'VUT', 'Venezuela': 'VEN',
  'Vietnam': 'VNM', 'Viet Nam': 'VNM', 'Yemen': 'YEM',
  'Zambia': 'ZMB', 'Zimbabwe': 'ZWE',
  // Regional/special
  'Kosovo under UNSCR 1244': 'XKX',
  "Democratic People's Republic of Korea": 'PRK',
}

export function getIso3(countryName) {
  if (!countryName) return null
  return COUNTRY_TO_ISO3[countryName] || COUNTRY_TO_ISO3[countryName.trim()] || null
}
